apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017       #porta do servidor
      targetPort: 27017 #porta do container
  type: ClusterIP